### ISSUE TITLE
Generating even / odd numbers

### ISSUE THREAD

**Issue by fstolz** [s-webber/projog#125]
This is a piece of code from a university course I once took:
```
geven(0).
geven(X) :- godd(Y), X is Y+1, X>0.
godd(1).
godd(X) :- geven(Y), X is Y+1, X>1.
```
geven generates all even natural numbers, godd generates all odd natural numbers. In Projog, however, only the first value for each rule is returned (0 for geven, 1 for godd).

**Comment by s-webber** [comment]
Thank you very much for raising this issue.

I have pushed a new commit which I believe should correct this behaviour.

If you are using projog as a maven dependency then you can include the latest version (including this bugfix) using:

```
<dependency>
  <groupId>org.projog</groupId>
  <artifactId>projog-core</artifactId>
  <version>0.2.1</version>
</dependency>
```

If you are using projog as a console application then you can download the latest version (including this bugfix) from:

http://www.projog.org/downloads.html

If you are having any other problems using Projog (or you have a suggestion for an enhancement) then please raise a new issue.

**Comment by s-webber** [comment]
Thank you for raising this issue. I am now considering it closed as the latest version of Projog includes a bugfix for this problem.

If you experience any other problems with Projog then please let me know by raising a new issue.
