### ISSUE TITLE
Adding a description to a rule

### ISSUE THREAD

**Issue by morandad** [s-webber/projog#138]
Hi,
Is there any way to add a description to a rule?
For example-
test(a,1).
test(b,2).
test(c,3).
test(1,a).
test(2,b).

testRule(X) :- test(X, Y), Y mod 2 =:= 0. // add a description - "id=ruleA".
testRule(X) :- test(X, Y), test(Y, X). // add a description - "id=ruleB".
testRule(X) :- test(X, Y). // add a description - "id=ruleC".

I need it, because in case of matching (QueryResult  is not empty), I want to know - which of the rules - was matched, and return its ID.

It's actually equal to QueryResult.predicateFactory.implications- an array that contains all the matching rules, right? But I need an ID.

Thanks.

**Comment by s-webber** [comment]
Thank you for raising this.

I might be misunderstanding the question, but I wonder if you can get the functionality you require by adding an extra argument to `testRule` which specifies the rule ID?

Here is an example of what I mean:

**Step 1.** Created `Issue138.pl` with the contents:

```
test(a,1).
test(b,2).
test(c,3).
test(1,a).
test(2,b).

testRule(1, X) :- test(X, Y), number(Y), Y mod 2 =:= 0.
testRule(2, X) :- test(X, Y), test(Y, X).
testRule(3, X) :- test(X, Y).
```

**Step 2.** Created `Issue138.java` with the contents:

```
import java.io.File;

import org.projog.api.Projog;
import org.projog.api.QueryResult;
import org.projog.api.QueryStatement;
import org.projog.core.term.Atom;
import org.projog.core.term.IntegerNumber;
import org.projog.core.term.Term;

public class Issue138 {
   private static final String ID = "Id";
   private static final String X = "X";

   public static void main(String[] args) {
      Projog p = new Projog();
      p.consultFile(new File("src/main/resources/Issue138.pl"));

      QueryStatement stmt = p.query("testRule(Id, X).");

      queryWithX(stmt, new Atom("a"));
      queryWithX(stmt, new Atom("b"));
      queryWithX(stmt, new Atom("c"));
      queryWithX(stmt, new IntegerNumber(1));
      queryWithX(stmt, new IntegerNumber(2));

      queryWithId(stmt, 1);
      queryWithId(stmt, 2);
      queryWithId(stmt, 3);

      query(stmt);
   }

   private static void queryWithX(QueryStatement stmt, Term inputTerm) {
      QueryResult r = stmt.getResult();
      r.setTerm(X, inputTerm);
      while (r.next()) {
         System.out.println("When the second argument of the query is: " + inputTerm + 
                            " then it matches with rule: " + r.getTerm(ID));
      }
      System.out.println();
   }

   private static void queryWithId(QueryStatement stmt, int id) {
      QueryResult r = stmt.getResult();
      r.setTerm(ID, new IntegerNumber(id));
      while (r.next()) {
         System.out.println("When the first argument of the query is: " + id + 
                            " then the second argument unifies with: " + r.getTerm(X));
      }
      System.out.println();
   }

   private static void query(QueryStatement stmt) {
      System.out.println("Results of querying with a variable as the second argument:");
      QueryResult r1 = stmt.getResult();
      while (r1.next()) {
         System.out.println(" Id = " + r1.getTerm(ID) + " X = " + r1.getTerm(X));
      }
   }
}
```

**Step 3.** Ran the Java program created in step 2 and got the following output:

```
When the second argument of the query is: a then it matches with rule: 2
When the second argument of the query is: a then it matches with rule: 3

When the second argument of the query is: b then it matches with rule: 1
When the second argument of the query is: b then it matches with rule: 2
When the second argument of the query is: b then it matches with rule: 3

When the second argument of the query is: c then it matches with rule: 3

When the second argument of the query is: 1 then it matches with rule: 2
When the second argument of the query is: 1 then it matches with rule: 3

When the second argument of the query is: 2 then it matches with rule: 2
When the second argument of the query is: 2 then it matches with rule: 3

When the first argument of the query is: 1 then the second argument unifies with: b

When the first argument of the query is: 2 then the second argument unifies with: a
When the first argument of the query is: 2 then the second argument unifies with: b
When the first argument of the query is: 2 then the second argument unifies with: 1
When the first argument of the query is: 2 then the second argument unifies with: 2

When the first argument of the query is: 3 then the second argument unifies with: a
When the first argument of the query is: 3 then the second argument unifies with: b
When the first argument of the query is: 3 then the second argument unifies with: c
When the first argument of the query is: 3 then the second argument unifies with: 1
When the first argument of the query is: 3 then the second argument unifies with: 2

Results of querying with a variable as the second argument:
 Id = 1 X = b
 Id = 2 X = a
 Id = 2 X = b
 Id = 2 X = 1
 Id = 2 X = 2
 Id = 3 X = a
 Id = 3 X = b
 Id = 3 X = c
 Id = 3 X = 1
 Id = 3 X = 2
```

I hope that makes sense and is a satisfactory solution to your problem. If not then please let me know and I'll take another look.

Thanks.

**Comment by morandad** [comment]
Hi,
First of all, thank you very much for the answer :) 
Your solution can help me, but it will cause me to make another changes in the predicates, and not just in the ruleID naming, in case of recursion in predicates.
For example-

father(Terah, Abraham).
father(Abraham, Isaac).
father(Isaac, Jacob).
father(Jacob, Judah).

ancestor(A,D) :- father(A,D).
ancestor(A,D) :- father(F,D), ancestor(A,F).

After adding an extra argument to "ancestor" to specify the ruleID:
ancestor(1,A,D) :- father(A,D).
ancestor(2,A,D) :- father(F,D), ancestor(A,F).

But the second pre-condition of the ruleID number 2, will never be assigned…
So I have to do more changes:
ancestor(2,A,D) :- father(F,D), ancestor(_,A,F).
Am I right?
I also thought about solution, similar to yours-
 Adding an extra predicate. "dummy" predicate.
So my rules will look like-

ancestor(A,D) :- father(A,D), ruleID(1).
ancestor(A,D) :- father(F,D), ancestor(A,F), ruleID(2).
And than to extract the predicate ruleID.
What do you think about it?

Thank you :)

**Comment by s-webber** [comment]
Thanks for the feedback.

I think my earlier suggestion - to add an extra argument to the rules which specifies the rule ID - isn't practical for more complex usages like you describe in your comment.

I wonder if a more appropriate approach is to use the debugging features of Prolog.

I will explain that in more detail as a comment on #143

**Comment by s-webber** [comment]
Closing this issue as it has been superseded by #143.
