### ISSUE TITLE
The QueryResult attributes

### ISSUE THREAD

**Issue by morandad** [s-webber/projog#143]
Hi,
I'll appreciate you looking on this example-

```
location (fridge, roomA, home).
location (microwave , roomA, home).
location (oven, roomA, home).
location (computer, roomC, home).
location (radio, roomC, home).
location (modem, roomC, home).
location (m1, roomD, home).
location (m2, roomD, home).
location(m3, roomD, home).
location (m4, roomD, home).
location (arirCond, roomB,home).
test (e1,roomA,roomB).
test (e1,roomC,roomB).
test (e2,roomD, roomB).
test (e3,roomE, roomB).
%test (e4, roomA, roomC). // line 16
testRule(1,A,B,C,D) :- test(Electricity ,A,B).
testRule (2,A,B,C,D) :- \+ test (Electricity ,A,B), location(_,A, home), location (_,B, home).
testRule (3,A',B,C,D) :- test(Electricity ,A,B), location (A',A, home).
testRule (4,A',B,C,D) :- \+ test (Electricity ,A,B), location (A',A, home), location (_,B, home).
testRule (5,A,B',C,D) :- test(Electricity ,A,B), location (B',B, home).
testRule (6,A,B',C,D) :- \+ test (Electricity ,A,B), location (B',B, home), location (_,A, home).
```

1.	
Let's assume we want to find the predicate testRule(roomA, roomC, C,D).
If line 16 is marked, the only matching is testRule (2,A,B,C,D).
If line 16 is unmarked, the only matching is testRule(1,A,B,C,D).
How I get this information from the QueryResult param?

I mean, if the code is:
QueryStatement s = p.query("testRule(roomA, roomC, C,D).");
QueryResult r = s.getResult();

while (r.next()) {
    // to do
    /*here I want to print the matching rule, and its pre conditions, with the appropriate assigning. 
    for example ( when line 16 is marked):*/

    testRule (2,A,B,C,D)-> testRule(2, roomA, roomC, C, D)
    And the preconditions:
    \+ test (Electricity ,A,B)->  \+ test (e4, roomA, roomC).
    location(_,A, home)-> all this options :
    location (fridge, roomA, home).
    location (microwave , roomA, home).
    location (oven, roomA, home).
    location (_,B, home)-> all this options:
    location (computer, roomC, home).
    location (radio, roomC, home).
    location (modem, roomC, home).
}
Is the predicateFactory hold this data? Or some another attribute?

2.  
In the "pl" file we have the predicates and the rules.
Is there anyway that we will find a matching just for the rules, and not for the predicates?
For example- If I will run the query :
QueryStatement s = p.query("(fridge, roomA, home)."); 
I don’t want to find a match, because it is a simple predicate and not a rule… or at least to understand that the matching I've found, is not kind of rule.
Hope this was clear…

Thank you very much, I really appreciate your help.

**Comment by s-webber** [comment]
Thank you for raising this.

I wonder if you can get the information you require by using the debugging features of Prolog.

I have added a demonstration of this approach to:

https://github.com/s-webber/projog-examples/tree/master/debugging-prolog-from-java

That approach calls `trace.` to enable debugging information. The application is notified of debugging information via the `CallStackObserver` class. `CallStackObserver` can be used to output which rules and facts have been matched.

When I run the `Issue143` class contained in that module then I get output like:

```
FIRST QUERY
---------------------------------------
ANSWER: roomA is the brother of roomB
Input: testRule(X, Y)

Matched testRule/2 clause number 1
Clause: testRule(A, B) :- test(Electricity, A, B)
Output: testRule(roomA, roomB)

Matched test/3 clause number 1
Clause: test(e1, roomA, roomB)
Output: test(e1, roomA, roomB)

---------------------------------------
ANSWER: roomC is the brother of roomB
Input: testRule(X, Y)

Matched testRule/2 clause number 1
Clause: testRule(A, B) :- test(Electricity, A, B)
Output: testRule(roomC, roomB)

Matched test/3 clause number 2
Clause: test(e1, roomC, roomB)
Output: test(e1, roomC, roomB)

---------------------------------------
ANSWER: roomD is the brother of roomB
Input: testRule(X, Y)

Matched testRule/2 clause number 1
Clause: testRule(A, B) :- test(Electricity, A, B)
Output: testRule(roomD, roomB)

Matched test/3 clause number 3
Clause: test(e2, roomD, roomB)
Output: test(e2, roomD, roomB)

---------------------------------------
ANSWER: roomE is the brother of roomB
Input: testRule(X, Y)

Matched testRule/2 clause number 1
Clause: testRule(A, B) :- test(Electricity, A, B)
Output: testRule(roomE, roomB)

Matched test/3 clause number 4
Clause: test(e3, roomE, roomB)
Output: test(e3, roomE, roomB)

SECOND QUERY
---------------------------------------
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 1
Clause: location(fridge, roomA, home)
Output: location(fridge, roomA, home)

Matched location/3 clause number 4
Clause: location(computer, roomC, home)
Output: location(computer, roomC, home)

---------------------------------------
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 1
Clause: location(fridge, roomA, home)
Output: location(fridge, roomA, home)

Matched location/3 clause number 5
Clause: location(radio, roomC, home)
Output: location(radio, roomC, home)

---------------------------------------
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 1
Clause: location(fridge, roomA, home)
Output: location(fridge, roomA, home)

Matched location/3 clause number 6
Clause: location(modem, roomC, home)
Output: location(modem, roomC, home)

---------------------------------------
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 2
Clause: location(microwave, roomA, home)
Output: location(microwave, roomA, home)

Matched location/3 clause number 4
Clause: location(computer, roomC, home)
Output: location(computer, roomC, home)

---------------------------------------
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 2
Clause: location(microwave, roomA, home)
Output: location(microwave, roomA, home)

Matched location/3 clause number 5
Clause: location(radio, roomC, home)
Output: location(radio, roomC, home)

---------------------------------------
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 2
Clause: location(microwave, roomA, home)
Output: location(microwave, roomA, home)

Matched location/3 clause number 6
Clause: location(modem, roomC, home)
Output: location(modem, roomC, home)

---------------------------------------
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 3
Clause: location(oven, roomA, home)
Output: location(oven, roomA, home)

Matched location/3 clause number 4
Clause: location(computer, roomC, home)
Output: location(computer, roomC, home)

---------------------------------------
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 3
Clause: location(oven, roomA, home)
Output: location(oven, roomA, home)

Matched location/3 clause number 5
Clause: location(radio, roomC, home)
Output: location(radio, roomC, home)

---------------------------------------
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 3
Clause: location(oven, roomA, home)
Output: location(oven, roomA, home)

Matched location/3 clause number 6
Clause: location(modem, roomC, home)
Output: location(modem, roomC, home)
```

Note that the example uses a snapshot version of `projog-core`. If you get a `Could not resolve dependencies` error while attempting to build the module then please follow the instructions in 

https://github.com/s-webber/projog-examples/blob/master/debugging-prolog-from-java/README.md

I hope that is useful to you. I have only looked at this briefly so there may be some issues with it. If you do experience any problems with this approach, or if you have any other feedback, then please let me know.

I will continue to think about your second question: 

> "Is there anyway that we will find a matching just for the rules, and not for the predicates?"

Thanks.

**Comment by morandad** [comment]
Hi, 
Thanks for your answer.

Your example- Isuue143- it's exactly what I need, but I didn't understand how to add the new version to my project.
I will explain-
First of all- I'm using Gradle, and not Maven to build my project. And I didn’t find in the "ReadMe" file, instructions how to use it with Gradle.
So I tried two things:
1.	I took your project from github, made JAR file from it, and added it as external library. 
So it recognize the projog library, but not the classes- CallStackObserver and CallStack, just the QueryStatement and the QueryResult.
And another problem that I added it not in the build.gradle file, so when I Rebuild it, this jar that wasn't added by gradle -was deleted….

(I've also found the JAR in this site: https://jar-download.com/artifacts/org.projog  , last updated in 9.9.18)

2.	I tried to add a dependency using jitpack https://jitpack.io/ , so I can give a reference to your github project- but also this solution isn't working…

```
repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }

}

dependencies {

    compile 'com.github.s-webber:projog:0.2.1'


}
```

I really don't know how to continue from here.
How to add projog to my gradle file, with the changes that you have committed for the debugging option?
Thanks.

**Comment by s-webber** [comment]
Hello,

Here is an example of a `build.gradle` file that worked for me:

```
apply plugin: 'java'
apply plugin: 'maven'

sourceCompatibility = 1.7
targetCompatibility = 1.7
tasks.withType(JavaCompile) {
   options.encoding = 'UTF-8'
}

repositories {
   maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
   maven { url "http://repo.maven.apache.org/maven2" }
}

dependencies {
   compile group: 'org.projog', name: 'projog-core', version:'0.3.0-SNAPSHOT'
   testCompile group: 'junit', name: 'junit', version:'4.12'
}
```

I have added that file to the `debugging-prolog-from-java` example project:

https://github.com/s-webber/projog-examples/tree/master/debugging-prolog-from-java

If that approach doesn't work for you then please let me know the error you are getting and I'll take another look.

Thanks.

**Comment by s-webber** [comment]
Regarding your second question:

> "Is there anyway that we will find a matching just for the rules, and not for the predicates? I don’t want to find a match, because it is a simple predicate and not a rule… or at least to understand that the matching I've found, is not kind of rule."

It is not possible to only match on rules, not facts. However it may be possible for you to determine, when there is a match, whether it was for a rule or a fact. To investigate this I have updated the `Issue143.java` example so that it now produces output like:

```
Input: testRule(roomA, roomC)

Matched testRule/2 clause number 2
Clause: testRule(A, B) :- not_test(Electricity, A, B) , location(_, A, home) , location(_, B, home)
Fact?   false
Output: testRule(roomA, roomC)

Matched not_test/3 clause number 1
Clause: not_test(Electricity, A, B) :- \+ test(Electricity, A, B)
Fact?   false
Output: not_test(Electricity, roomA, roomC)

Matched location/3 clause number 3
Clause: location(oven, roomA, home)
Fact?   true
Output: location(oven, roomA, home)

Matched location/3 clause number 6
Clause: location(modem, roomC, home)
Fact?   true
Output: location(modem, roomC, home)
```

Note that - unlike the example output from an earlier comment - it now includes entries like `Fact?   true` and `Fact?   false`. This functionality is provide by the `isFact` method of `Issue143.java`.

The `isFact` method considers a clause to be a fact if has an antecedant (i.e. rule body) of `true`. This means that, for example, the following clauses would be classified as facts: `example(x).`, `example(X,Y).`, `example(x) :- true.` and `example(x, y, z) :- true.` while the following clauses would _not_ be classified as facts: `example(X, Y) :- X is Y * 2.`, `example(x) :- fail` and `example(x, y) :- write('hello').`.

Note that if a clause is written without an antecedant being explicitly defined - i.e. the clause is written without a `:-` - then it is assumed to have a antecedant  of `true`, meaning `example(X).` and `example(X) :- true.` are considered identical.

**Comment by morandad** [comment]
Hi,
Thanks for your build.gradle file!
Now the libraries- org.projog.api.Projog, org.projog.api.QueryResult, org.projog.api.QueryStatement are recognized, but still I'm getting the error- 
> Cannot resolve symbol CallStackObserver 
(And also  CallStack, But- Projog, QueryStatement and QueryResult classes- are resolved )
![image](https://user-images.githubusercontent.com/28728137/47264538-c88b2780-d521-11e8-90e3-e0df946d6059.png)

What do you think the problem is?
Thanks :)

**Comment by morandad** [comment]
Regarding to my second question-
It's great!
Thank you :)

**Comment by morandad** [comment]
Oh!
I didn't notice it before, but I've just seen that the CallStackObserver and CallStack are separated classes , and not part of the projog-core:0.3.0-SNAPSHOT!
So I added them. and now I will check the whole scenario.
The problem wasn't in the build.gradle file, it was my mistake. Sorry!
Thank you!!

**Comment by s-webber** [comment]
OK, no worries. If there is anymore I can do to help then please let me know. Thanks.

**Comment by morandad** [comment]
It works perfect!
Thanks for all :)

**Comment by s-webber** [comment]
Glad I could help. I am now closing this issue.

If you experience any other problems with Projog then please let me know by raising a new issue. Thanks.
